### PR TITLE
Rebase onto 20230120

### PR DESCRIPTION
**Pull request by 13r0ck**
For https://github.com/pop-os/mesa/pull/13 and 7900XT GPUs

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
Just to track what I've looked at:
 - [x] Lemp11
 - [ ] Oryp10
 - [ ] DevOne
 - [x] MiraB4
 - [ ] MegaR1

**Comment by XV-02** [comment]
Not seeing any issues with any of the nvme drives I've tested, so calling those good for the moment.

**Comment by XV-02** [comment]
It looks like the 7000 series AMD gpus have an xorg config related issue which causes the mouse-cursor to not render. There appear to be some fixes in the wild, but it looks like it effects Linux generally. At least [one such fix](https://www.reddit.com/r/linux_gaming/comments/10oi4k2/amd_rx_7000_series_gpu_cursor_invisible_in_xorg/) seemed to resolve the issue (accounting for the differences in appropriate config location)

**Review by leviport — APPROVED** [review]
No mouse cursor is better than no booting, so I think this is still ok to release since it passed the rest of our tests. We'll just have to remember to fix the xorg mouse cursor issue before we sell those cards in the Thelio line.

**Pull request merged**
