### PR TITLE
Linux firmware 20220329.git681281e4

### PR DESCRIPTION
**Pull request by jackpot51**
Backport from Ubuntu 22.04

### CODE REVIEW

**Comment by XV-02** [comment]
In the midst of testing, but I did notice that this required `sudo apt full-upgrade` in 20.04.

**Comment by XV-02** [comment]
# Pop 20.04

- [x] Updating to new Linux-Firmware works with `apt update && apt upgrade`
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [x] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [x] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

# Conclusion: Looks good for Pop 20.04!

**Comment by XV-02** [comment]
# Pop 21.10

- [x] Updating to new Linux-Firmware works with `apt update && apt upgrade`
- [x] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [x] Mic in
- [x] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [x] Display Port
    - [x] HDMI
- [X] Video out via:
    - [x] DisplayPort
    - [x] HDMI
- [x] Thunderbolt docking station:
    - [x] HDMI and DisplayPort
    - [x] External storage device
    - [x] Networking
- [ ] Suspend and resume:
    - [x] Switchable graphics laptops 
        - [x] In Hybrid graphics mode
        - [x] In Nvidia graphics mode
        - [x] In Integrated graphics mode
    - [x] Nvidia desktop
    - [x] Discrete AMD desktop
    - [x] Integrated Intel desktop
    - [x] Integrated AMD desktop
    - [ ] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [x] Steam
    - [x] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [x] Steam launches from launcher
    - [x] Linux native game installs and runs
    - [x] Proton game installs and runs
- [x] Virtualbox installs and works as expected

# Conclusion: Pending

**Comment by leviport** [comment]
# Pop 22.04

- [] Updating to new Linux-Firmware works with `apt update && apt upgrade`
- [] `system76-power` still opperates as expected (across Intel/NVIDIA/switchable machines)
- [] Mic in
- [] Audio out:
    - [] Laptop's built-in speakers
    - [] Headphones
    - [] Display Port
    - [] HDMI
- [] Video out via:
    - [] DisplayPort
    - [] HDMI
- [] Thunderbolt docking station:
    - [] HDMI and DisplayPort
    - [] External storage device
    - [] Networking
- [] Suspend and resume:
    - [] Switchable graphics laptops 
        - [] In Hybrid graphics mode
        - [] In Nvidia graphics mode
        - [] In Integrated graphics mode
    - [] Nvidia desktop
    - [] Discrete AMD desktop
    - [] Integrated Intel desktop
    - [] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [] Steam
    - [] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [] Steam launches from launcher
    - [] Linux native game installs and runs
    - [] Proton game installs and runs
- [] Virtualbox installs and works as expected

# Conclusion: Pending

**Comment by XV-02** [comment]
## Issue: 22.04 Debug 54 (Beta release 2)

With the first Beta release, I wasn't witnessing issues with 22.04 and linux-firmware-jammy. With the debug 54 iso, which will soon be Beta 2, I'm having frequent hangs after decrypt. I also plan to test an unencrypted install after addressing other tests for OS functionality with the linux-firmware update.

This issue is noticed on both a Gaze16-3060-B and a Galp5-3050.

I pulled journalctl logs from hung boots:
[log1.txt](https://github.com/pop-os/linux-firmware/files/8429934/log1.txt)
[log2.txt](https://github.com/pop-os/linux-firmware/files/8429938/log2.txt)

**Comment by XV-02** [comment]
# Ubuntu 20.04

- [x] Updating to new Linux-Firmware works with `apt update && apt upgrade`
- [x] `system76-power` still operates as expected (across Intel/NVIDIA/switchable machines)
- [ ] Mic in
- [ ] Audio out:
    - [x] Laptop's built-in speakers
    - [x] Headphones
    - [ ] Display Port
    - [ ] HDMI
- [ ] Video out via:
    - [ ] DisplayPort
    - [ ] HDMI
- [ ] Thunderbolt docking station:
    - [ ] HDMI and DisplayPort
    - [ ] External storage device
    - [ ] Networking
- [ ] Suspend and resume:
    - [ ] Switchable graphics laptops 
        - [ ] In Hybrid graphics mode
        - [ ] In Nvidia graphics mode
        - [ ] In Integrated graphics mode
    - [ ] Nvidia desktop
    - [ ] Discrete AMD desktop
    - [ ] Integrated Intel desktop
    - [ ] Integrated AMD desktop
    - [x] 150 suspend/resume cycles (`fwts s3 --s3-multiple 150`)
- [ ] Steam
    - [ ] Steam installs via the Pop!_OS .deb in Pop!_Shop
    - [ ] Steam launches from launcher
    - [ ] Linux native game installs and runs
    - [ ] Proton game installs and runs
- [ ] Virtualbox installs and works as expected

# Conclusion: Pending

**Comment by XV-02** [comment]
## Potential Blocker: Ubuntu 20.04 Requires `apt full-upgrade`

`sudo apt full-upgrade` was required in Ubuntu 20.04.

**Review by XV-02 — APPROVED** [review]
All our test OSs passed, barring Ubuntu/Pop 20.04, which required a `full-upgrade` command.

@jackpot51 The issue noticed as a potential blocker with 22.04 seems resolved by a recent Plymouth roll back. The `full-upgrade` requirement isn't present if upgrading from the currently released Linux-Firmware package, but from the firmware packages shipped on the 20.04 ISOs, it is.

**Pull request merged**
