### PR TITLE
Update Intel Bluetooth firmware to 22.50.04

### LINKED ISSUE #13: Bluetooth random disconnects intel(R) AX200
Hi, I have an intel AX200, and while the wifi works perfectly, the Bluetooth randomly disconnects from devices. 
This seems to be a common error that intel has fixed a few days ago: [Reddit Broken ax200](https://www.reddit.com/r/linuxhardware/comments/m21yhj/fyi_bluetooth_on_intel_ax200_currently_broken/)

It is possible to add those fixes in the package?

Thanks!

### PR DESCRIPTION
**Pull request by jackpot51**
Will force push to master when approved. Might fix #13

### CODE REVIEW

**Comment by leviport** [comment]
I'm still seeing bluetooth drop out with my headset. I'll continue using this patch for another day or so to see if they're at least less frequent. It's hard to tell without sustained usage.

**Comment by leviport** [comment]
The disconnects don't seem any less frequent. Since I'm not seeing any improvements, I'm not sure this is worth merging.

**Comment by leviport** [comment]
This may have started working properly? On Monday, I had this patch installed and experienced no bluetooth disconnects. On Tuesday, I removed it to see if some other update was what fixed it and experienced quite a few bluetooth disconnects. I've re-added it today, and if I don't see a disconnect in the next couple days, I'm going to assume it fixed it. Why it didn't fix it before is still a bit of a disturbing mystery though.

**Comment by scrufulufugus** [comment]
I was having Bluetooth disconnects every 10-20 minutes before. After applying this patch I have had no disconnects in about 6 hours of Bluetooth usage.

**Comment by leviport** [comment]
@scrufulufugus Keep trying for a while. It can be super random for me. Sometimes I'll get three within 15 minutes, and sometimes it'll go hours without disconnecting once.

That said, I used my bluetooth headset all day today with this patch installed, and I haven't had a single disconnect. I'm starting to think this at least makes it better than it was.

**Review by leviport — APPROVED** [review]
I experienced zero bluetooth disconnects in the last couple days with pretty heavy usage of my bluetooth headset, which previously disconnected fairly frequently. So this either fixes it entirely, or makes it much less frequent, as reported by @scrufulufugus. Either way, it seems like an improvement.

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
